services:
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    depends_on:
      - minio
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://test-bucket/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH__STYLE__ACCESS=true
      - CATALOG_CATALOG__IMPL=org.apache.iceberg.jdbc.JdbcCatalog
      - CATALOG_URI=jdbc:postgresql://iceberg_rest-db:5432/iceberg_restdb
      - CATALOG_JDBC_USER=iceberg_rest
      - CATALOG_JDBC_PASSWORD=password
      # NOTE: I was not able to make file metadata work with the HadoopCatalog
      # - CATALOG_CATALOG__IMPL=org.apache.iceberg.hadoop.HadoopCatalog
      # - CATALOG_FS_DEFAULT__FS=s3a://test-bucket/
      # - CATALOG_FS_S3A_ENDPOINT=http://minio:9000
      # - CATALOG_FS_S3A_PATH__STYLE__ACCESS=true
      # - CATALOG_FS_S3A_ACCESS__KEY=admin
      # - CATALOG_FS_S3A_SECRET__KEY=password

  minio:
    image: minio/minio
    container_name: minio
    depends_on:
      iceberg_rest-db:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_SITE_REGION=us-east-1
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]

  createbuckets:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add minio http://minio:9000 admin password; do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/test-bucket || true;
      /usr/bin/mc mb minio/test-bucket;
      /usr/bin/mc policy set public minio/test-bucket;
      tail -f /dev/null;
      exit 0;"

  iceberg_rest-db:
    image: postgres:latest
    container_name: iceberg-rest-db
    init: true
    environment:
      POSTGRES_DB: iceberg_restdb
      POSTGRES_USER: iceberg_rest
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "iceberg_rest", "-d", "iceberg_restdb" ]
      interval: 5s
      retries: 5